const API_KEY = process.env.EXPO_PUBLIC_API_KEY;

export const getMovies = async (): Promise<Movie[]> => {
  return movies;

  const movieIds = ['tt0111161', 'tt0068646', 'tt0468569', 'tt0108052'];
  const result = await Promise.all(movieIds.map(async (id) => await getMovieDetails(id)));
  return result;
};

export const getSearchResults = async (query: string): Promise<MovieSearchResult[]> => {
  const response = await fetch(
    `https://www.omdbapi.com/?apikey=${API_KEY}&s=${encodeURIComponent(query)}`
  );

  const data = await response.json();
  console.log({ data });
  return data.Search || [];
};

export const getMovieDetails = async (id: string): Promise<any> => {
  const response = await fetch(`https://www.omdbapi.com/?apikey=${API_KEY}&i=${id}`);
  return await response.json();
};

const movies = [
  {
    Title: 'The Shawshank Redemption',
    Year: '1994',
    Rated: 'R',
    Released: '14 Oct 1994',
    Runtime: '142 min',
    Genre: 'Drama',
    Director: 'Frank Darabont',
    Writer: 'Stephen King, Frank Darabont',
    Actors: 'Tim Robbins, Morgan Freeman, Bob Gunton',
    Plot: 'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Nominated for 7 Oscars. 21 wins & 42 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.3/10' },
      { Source: 'Rotten Tomatoes', Value: '89%' },
      { Source: 'Metacritic', Value: '82/100' },
    ],
    Metascore: '82',
    imdbRating: '9.3',
    imdbVotes: '2,907,297',
    imdbID: 'tt0111161',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$28,767,189',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Godfather',
    Year: '1972',
    Rated: 'R',
    Released: '24 Mar 1972',
    Runtime: '175 min',
    Genre: 'Crime, Drama',
    Director: 'Francis Ford Coppola',
    Writer: 'Mario Puzo, Francis Ford Coppola',
    Actors: 'Marlon Brando, Al Pacino, James Caan',
    Plot: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    Language: 'English, Italian, Latin',
    Country: 'United States',
    Awards: 'Won 3 Oscars. 31 wins & 31 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.2/10' },
      { Source: 'Rotten Tomatoes', Value: '97%' },
      { Source: 'Metacritic', Value: '100/100' },
    ],
    Metascore: '100',
    imdbRating: '9.2',
    imdbVotes: '2,024,175',
    imdbID: 'tt0068646',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$136,381,073',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Dark Knight',
    Year: '2008',
    Rated: 'PG-13',
    Released: '18 Jul 2008',
    Runtime: '152 min',
    Genre: 'Action, Crime, Drama',
    Director: 'Christopher Nolan',
    Writer: 'Jonathan Nolan, Christopher Nolan, David S. Goyer',
    Actors: 'Christian Bale, Heath Ledger, Aaron Eckhart',
    Plot: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    Language: 'English, Mandarin',
    Country: 'United States, United Kingdom',
    Awards: 'Won 2 Oscars. 163 wins & 164 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.0/10' },
      { Source: 'Rotten Tomatoes', Value: '94%' },
      { Source: 'Metacritic', Value: '84/100' },
    ],
    Metascore: '84',
    imdbRating: '9.0',
    imdbVotes: '2,886,071',
    imdbID: 'tt0468569',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$534,987,076',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: "Schindler's List",
    Year: '1993',
    Rated: 'R',
    Released: '04 Feb 1994',
    Runtime: '195 min',
    Genre: 'Biography, Drama, History',
    Director: 'Steven Spielberg',
    Writer: 'Thomas Keneally, Steven Zaillian',
    Actors: 'Liam Neeson, Ralph Fiennes, Ben Kingsley',
    Plot: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    Language: 'English, Hebrew, German, Polish, Latin',
    Country: 'United States',
    Awards: 'Won 7 Oscars. 91 wins & 49 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.0/10' },
      { Source: 'Rotten Tomatoes', Value: '98%' },
      { Source: 'Metacritic', Value: '95/100' },
    ],
    Metascore: '95',
    imdbRating: '9.0',
    imdbVotes: '1,462,041',
    imdbID: 'tt0108052',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$96,898,818',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Lord of the Rings: The Return of the King',
    Year: '2003',
    Rated: 'PG-13',
    Released: '17 Dec 2003',
    Runtime: '201 min',
    Genre: 'Action, Adventure, Drama',
    Director: 'Peter Jackson',
    Writer: 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens',
    Actors: 'Elijah Wood, Viggo Mortensen, Ian McKellen',
    Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    Language: 'English, Quenya, Old English, Sindarin',
    Country: 'New Zealand, United States',
    Awards: 'Won 11 Oscars. 215 wins & 124 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.0/10' },
      { Source: 'Rotten Tomatoes', Value: '94%' },
      { Source: 'Metacritic', Value: '94/100' },
    ],
    Metascore: '94',
    imdbRating: '9.0',
    imdbVotes: '1,989,103',
    imdbID: 'tt0167260',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$381,201,096',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: '12 Angry Men',
    Year: '1957',
    Rated: 'Approved',
    Released: '10 Apr 1957',
    Runtime: '96 min',
    Genre: 'Crime, Drama',
    Director: 'Sidney Lumet',
    Writer: 'Reginald Rose',
    Actors: 'Henry Fonda, Lee J. Cobb, Martin Balsam',
    Plot: 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Nominated for 3 Oscars. 16 wins & 12 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.0/10' },
      { Source: 'Rotten Tomatoes', Value: '100%' },
      { Source: 'Metacritic', Value: '97/100' },
    ],
    Metascore: '97',
    imdbRating: '9.0',
    imdbVotes: '873,385',
    imdbID: 'tt0050083',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Godfather Part II',
    Year: '1974',
    Rated: 'R',
    Released: '18 Dec 1974',
    Runtime: '202 min',
    Genre: 'Crime, Drama',
    Director: 'Francis Ford Coppola',
    Writer: 'Francis Ford Coppola, Mario Puzo',
    Actors: 'Al Pacino, Robert De Niro, Robert Duvall',
    Plot: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    Language: 'English, Italian, Spanish, Latin, Sicilian',
    Country: 'United States',
    Awards: 'Won 6 Oscars. 17 wins & 21 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.0/10' },
      { Source: 'Rotten Tomatoes', Value: '96%' },
      { Source: 'Metacritic', Value: '90/100' },
    ],
    Metascore: '90',
    imdbRating: '9.0',
    imdbVotes: '1,371,756',
    imdbID: 'tt0071562',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$47,834,595',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Lord of the Rings: The Fellowship of the Ring',
    Year: '2001',
    Rated: 'PG-13',
    Released: '19 Dec 2001',
    Runtime: '178 min',
    Genre: 'Action, Adventure, Drama',
    Director: 'Peter Jackson',
    Writer: 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens',
    Actors: 'Elijah Wood, Ian McKellen, Orlando Bloom',
    Plot: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    Language: 'English, Sindarin',
    Country: 'New Zealand, United States',
    Awards: 'Won 4 Oscars. 125 wins & 127 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.9/10' },
      { Source: 'Rotten Tomatoes', Value: '92%' },
      { Source: 'Metacritic', Value: '92/100' },
    ],
    Metascore: '92',
    imdbRating: '8.9',
    imdbVotes: '2,017,935',
    imdbID: 'tt0120737',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$318,572,165',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Pulp Fiction',
    Year: '1994',
    Rated: 'R',
    Released: '14 Oct 1994',
    Runtime: '154 min',
    Genre: 'Crime, Drama',
    Director: 'Quentin Tarantino',
    Writer: 'Quentin Tarantino, Roger Avary',
    Actors: 'John Travolta, Uma Thurman, Samuel L. Jackson',
    Plot: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    Language: 'English, Spanish, French',
    Country: 'United States',
    Awards: 'Won 1 Oscar. 69 wins & 72 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.9/10' },
      { Source: 'Rotten Tomatoes', Value: '92%' },
      { Source: 'Metacritic', Value: '95/100' },
    ],
    Metascore: '95',
    imdbRating: '8.9',
    imdbVotes: '2,232,974',
    imdbID: 'tt0110912',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$107,928,762',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: '12th Fail',
    Year: '2023',
    Rated: 'N/A',
    Released: '27 Oct 2023',
    Runtime: '147 min',
    Genre: 'Biography, Drama',
    Director: 'Vidhu Vinod Chopra',
    Writer: 'Vidhu Vinod Chopra, Jaskunwar Kohli, Anurag Pathak',
    Actors: 'Vikrant Massey, Medha Shankr, Anant Joshi',
    Plot: 'The real-life story of IPS Officer Manoj Kumar Sharma and IRS Officer Shraddha Joshi.',
    Language: 'Hindi, Malayalam, Tamil, Telugu, Kannada',
    Country: 'India',
    Awards: '23 wins & 26 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZDI4OTM1ZjMtOWQxMC00OTY5LTg3NjQtMjlhMWVjODFlYTY4XkEyXkFqcGdeQXVyMTYzMTU3Njgx._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.9/10' },
      { Source: 'Rotten Tomatoes', Value: '91%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.9',
    imdbVotes: '118,788',
    imdbID: 'tt23849204',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Forrest Gump',
    Year: '1994',
    Rated: 'PG-13',
    Released: '06 Jul 1994',
    Runtime: '142 min',
    Genre: 'Drama, Romance',
    Director: 'Robert Zemeckis',
    Writer: 'Winston Groom, Eric Roth',
    Actors: 'Tom Hanks, Robin Wright, Gary Sinise',
    Plot: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 6 Oscars. 51 wins & 74 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.8/10' },
      { Source: 'Rotten Tomatoes', Value: '76%' },
      { Source: 'Metacritic', Value: '82/100' },
    ],
    Metascore: '82',
    imdbRating: '8.8',
    imdbVotes: '2,271,898',
    imdbID: 'tt0109830',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$330,455,270',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Inception',
    Year: '2010',
    Rated: 'PG-13',
    Released: '16 Jul 2010',
    Runtime: '148 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'Christopher Nolan',
    Writer: 'Christopher Nolan',
    Actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
    Plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.',
    Language: 'English, Japanese, French',
    Country: 'United States, United Kingdom',
    Awards: 'Won 4 Oscars. 159 wins & 220 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.8/10' },
      { Source: 'Rotten Tomatoes', Value: '87%' },
      { Source: 'Metacritic', Value: '74/100' },
    ],
    Metascore: '74',
    imdbRating: '8.8',
    imdbVotes: '2,564,438',
    imdbID: 'tt1375666',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$292,587,330',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Fight Club',
    Year: '1999',
    Rated: 'R',
    Released: '15 Oct 1999',
    Runtime: '139 min',
    Genre: 'Drama',
    Director: 'David Fincher',
    Writer: 'Chuck Palahniuk, Jim Uhls',
    Actors: 'Brad Pitt, Edward Norton, Meat Loaf',
    Plot: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    Language: 'English',
    Country: 'Germany, United States',
    Awards: 'Nominated for 1 Oscar. 12 wins & 38 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.8/10' },
      { Source: 'Rotten Tomatoes', Value: '80%' },
      { Source: 'Metacritic', Value: '67/100' },
    ],
    Metascore: '67',
    imdbRating: '8.8',
    imdbVotes: '2,338,157',
    imdbID: 'tt0137523',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$37,030,102',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Lord of the Rings: The Two Towers',
    Year: '2002',
    Rated: 'PG-13',
    Released: '18 Dec 2002',
    Runtime: '179 min',
    Genre: 'Action, Adventure, Drama',
    Director: 'Peter Jackson',
    Writer: 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens',
    Actors: 'Elijah Wood, Ian McKellen, Viggo Mortensen',
    Plot: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
    Language: 'English, Sindarin, Old English',
    Country: 'New Zealand, United States',
    Awards: 'Won 2 Oscars. 132 wins & 138 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.8/10' },
      { Source: 'Rotten Tomatoes', Value: '95%' },
      { Source: 'Metacritic', Value: '87/100' },
    ],
    Metascore: '87',
    imdbRating: '8.8',
    imdbVotes: '1,797,690',
    imdbID: 'tt0167261',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$345,518,923',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Good, the Bad and the Ugly',
    Year: '1966',
    Rated: 'R',
    Released: '29 Dec 1967',
    Runtime: '178 min',
    Genre: 'Adventure, Drama, Western',
    Director: 'Sergio Leone',
    Writer: 'Luciano Vincenzoni, Sergio Leone, Agenore Incrocci',
    Actors: 'Clint Eastwood, Eli Wallach, Lee Van Cleef',
    Plot: 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',
    Language: 'Italian, English',
    Country: 'Italy, Spain, West Germany',
    Awards: '2 wins & 5 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.8/10' },
      { Source: 'Rotten Tomatoes', Value: '97%' },
      { Source: 'Metacritic', Value: '90/100' },
    ],
    Metascore: '90',
    imdbRating: '8.8',
    imdbVotes: '815,008',
    imdbID: 'tt0060196',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$25,100,000',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Interstellar',
    Year: '2014',
    Rated: 'PG-13',
    Released: '07 Nov 2014',
    Runtime: '169 min',
    Genre: 'Adventure, Drama, Sci-Fi',
    Director: 'Christopher Nolan',
    Writer: 'Jonathan Nolan, Christopher Nolan',
    Actors: 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
    Plot: 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
    Language: 'English',
    Country: 'United States, United Kingdom, Canada',
    Awards: 'Won 1 Oscar. 44 wins & 148 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.7/10' },
      { Source: 'Rotten Tomatoes', Value: '73%' },
      { Source: 'Metacritic', Value: '74/100' },
    ],
    Metascore: '74',
    imdbRating: '8.7',
    imdbVotes: '2,126,853',
    imdbID: 'tt0816692',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$188,020,017',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Matrix',
    Year: '1999',
    Rated: 'R',
    Released: '31 Mar 1999',
    Runtime: '136 min',
    Genre: 'Action, Sci-Fi',
    Director: 'Lana Wachowski, Lilly Wachowski',
    Writer: 'Lilly Wachowski, Lana Wachowski',
    Actors: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
    Plot: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    Language: 'English',
    Country: 'United States, Australia',
    Awards: 'Won 4 Oscars. 42 wins & 52 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.7/10' },
      { Source: 'Rotten Tomatoes', Value: '83%' },
      { Source: 'Metacritic', Value: '73/100' },
    ],
    Metascore: '73',
    imdbRating: '8.7',
    imdbVotes: '2,070,350',
    imdbID: 'tt0133093',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$172,076,928',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Goodfellas',
    Year: '1990',
    Rated: 'R',
    Released: '21 Sep 1990',
    Runtime: '145 min',
    Genre: 'Biography, Crime, Drama',
    Director: 'Martin Scorsese',
    Writer: 'Nicholas Pileggi, Martin Scorsese',
    Actors: 'Robert De Niro, Ray Liotta, Joe Pesci',
    Plot: 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.',
    Language: 'English, Italian, Hebrew, Yiddish',
    Country: 'United States',
    Awards: 'Won 1 Oscar. 44 wins & 38 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.7/10' },
      { Source: 'Rotten Tomatoes', Value: '95%' },
      { Source: 'Metacritic', Value: '92/100' },
    ],
    Metascore: '92',
    imdbRating: '8.7',
    imdbVotes: '1,265,270',
    imdbID: 'tt0099685',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$46,909,721',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: "One Flew Over the Cuckoo's Nest",
    Year: '1975',
    Rated: 'R',
    Released: '19 Nov 1975',
    Runtime: '133 min',
    Genre: 'Drama',
    Director: 'Milos Forman',
    Writer: 'Lawrence Hauben, Bo Goldman, Ken Kesey',
    Actors: 'Jack Nicholson, Louise Fletcher, Michael Berryman',
    Plot: 'In the Fall of 1963, a Korean War veteran and criminal pleads insanity and is admitted to a mental institution, where he rallies up the scared patients against the tyrannical nurse.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 5 Oscars. 42 wins & 20 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.7/10' },
      { Source: 'Rotten Tomatoes', Value: '93%' },
      { Source: 'Metacritic', Value: '84/100' },
    ],
    Metascore: '84',
    imdbRating: '8.7',
    imdbVotes: '1,077,325',
    imdbID: 'tt0073486',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$108,981,275',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Star Wars: Episode V - The Empire Strikes Back',
    Year: '1980',
    Rated: 'PG',
    Released: '18 Jun 1980',
    Runtime: '124 min',
    Genre: 'Action, Adventure, Fantasy',
    Director: 'Irvin Kershner',
    Writer: 'Leigh Brackett, Lawrence Kasdan, George Lucas',
    Actors: 'Mark Hamill, Harrison Ford, Carrie Fisher',
    Plot: 'After the Rebel Alliance are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 1 Oscar. 27 wins & 20 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.7/10' },
      { Source: 'Rotten Tomatoes', Value: '95%' },
      { Source: 'Metacritic', Value: '82/100' },
    ],
    Metascore: '82',
    imdbRating: '8.7',
    imdbVotes: '1,390,562',
    imdbID: 'tt0080684',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$292,753,960',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Dune: Part Two',
    Year: '2024',
    Rated: 'PG-13',
    Released: '01 Mar 2024',
    Runtime: '166 min',
    Genre: 'Action, Adventure, Drama',
    Director: 'Denis Villeneuve',
    Writer: 'Denis Villeneuve, Jon Spaihts, Frank Herbert',
    Actors: 'Timothée Chalamet, Zendaya, Rebecca Ferguson',
    Plot: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    Language: 'English',
    Country:
      'United States, Canada, United Arab Emirates, Hungary, Italy, New Zealand, Jordan, Gambia',
    Awards: '4 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BN2QyZGU4ZDctOWMzMy00NTc5LThlOGQtODhmNDI1NmY5YzAwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '92%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.6',
    imdbVotes: '449,148',
    imdbID: 'tt15239678',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$282,144,358',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Silence of the Lambs',
    Year: '1991',
    Rated: 'R',
    Released: '14 Feb 1991',
    Runtime: '118 min',
    Genre: 'Crime, Drama, Thriller',
    Director: 'Jonathan Demme',
    Writer: 'Thomas Harris, Ted Tally',
    Actors: 'Jodie Foster, Anthony Hopkins, Scott Glenn',
    Plot: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    Language: 'English, Latin',
    Country: 'United States',
    Awards: 'Won 5 Oscars. 71 wins & 50 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '95%' },
      { Source: 'Metacritic', Value: '86/100' },
    ],
    Metascore: '86',
    imdbRating: '8.6',
    imdbVotes: '1,556,805',
    imdbID: 'tt0102926',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$130,742,922',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Se7en',
    Year: '1995',
    Rated: 'R',
    Released: '22 Sep 1995',
    Runtime: '127 min',
    Genre: 'Crime, Drama, Mystery',
    Director: 'David Fincher',
    Writer: 'Andrew Kevin Walker',
    Actors: 'Morgan Freeman, Brad Pitt, Kevin Spacey',
    Plot: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Nominated for 1 Oscar. 29 wins & 43 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '83%' },
      { Source: 'Metacritic', Value: '65/100' },
    ],
    Metascore: '65',
    imdbRating: '8.6',
    imdbVotes: '1,809,546',
    imdbID: 'tt0114369',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$100,125,643',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Spider-Man: Across the Spider-Verse',
    Year: '2023',
    Rated: 'PG',
    Released: '02 Jun 2023',
    Runtime: '140 min',
    Genre: 'Animation, Action, Adventure',
    Director: 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
    Writer: 'Phil Lord, Christopher Miller, Dave Callaham',
    Actors: 'Shameik Moore, Hailee Steinfeld, Brian Tyree Henry',
    Plot: 'Miles Morales catapults across the multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a ...',
    Language: 'English',
    Country: 'United States',
    Awards: 'Nominated for 1 Oscar. 102 wins & 163 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '95%' },
      { Source: 'Metacritic', Value: '86/100' },
    ],
    Metascore: '86',
    imdbRating: '8.6',
    imdbVotes: '378,518',
    imdbID: 'tt9362722',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$381,593,754',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Saving Private Ryan',
    Year: '1998',
    Rated: 'R',
    Released: '24 Jul 1998',
    Runtime: '169 min',
    Genre: 'Drama, War',
    Director: 'Steven Spielberg',
    Writer: 'Robert Rodat',
    Actors: 'Tom Hanks, Matt Damon, Tom Sizemore',
    Plot: 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
    Language: 'English, French, German, Czech',
    Country: 'United States',
    Awards: 'Won 5 Oscars. 79 wins & 75 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '94%' },
      { Source: 'Metacritic', Value: '91/100' },
    ],
    Metascore: '91',
    imdbRating: '8.6',
    imdbVotes: '1,505,477',
    imdbID: 'tt0120815',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$217,049,603',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Terminator 2: Judgment Day',
    Year: '1991',
    Rated: 'R',
    Released: '03 Jul 1991',
    Runtime: '137 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'James Cameron',
    Writer: 'James Cameron, William Wisher',
    Actors: 'Arnold Schwarzenegger, Linda Hamilton, Edward Furlong',
    Plot: 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten year old son John from an even more advanced and powerful cyborg.',
    Language: 'English, Spanish',
    Country: 'United States, France',
    Awards: 'Won 4 Oscars. 39 wins & 33 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '91%' },
      { Source: 'Metacritic', Value: '75/100' },
    ],
    Metascore: '75',
    imdbRating: '8.6',
    imdbVotes: '1,180,148',
    imdbID: 'tt0103064',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$205,881,154',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Star Wars: Episode IV - A New Hope',
    Year: '1977',
    Rated: 'PG',
    Released: '25 May 1977',
    Runtime: '121 min',
    Genre: 'Action, Adventure, Fantasy',
    Director: 'George Lucas',
    Writer: 'George Lucas',
    Actors: 'Mark Hamill, Harrison Ford, Carrie Fisher',
    Plot: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth ...",
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 6 Oscars. 67 wins & 31 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '93%' },
      { Source: 'Metacritic', Value: '90/100' },
    ],
    Metascore: '90',
    imdbRating: '8.6',
    imdbVotes: '1,456,358',
    imdbID: 'tt0076759',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$460,998,507',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Spirited Away',
    Year: '2001',
    Rated: 'PG',
    Released: '28 Mar 2003',
    Runtime: '125 min',
    Genre: 'Animation, Adventure, Family',
    Director: 'Hayao Miyazaki',
    Writer: 'Hayao Miyazaki',
    Actors: 'Daveigh Chase, Suzanne Pleshette, Miyu Irino',
    Plot: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.",
    Language: 'Japanese, English',
    Country: 'Japan',
    Awards: 'Won 1 Oscar. 58 wins & 31 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '96%' },
      { Source: 'Metacritic', Value: '96/100' },
    ],
    Metascore: '96',
    imdbRating: '8.6',
    imdbVotes: '859,254',
    imdbID: 'tt0245429',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$15,205,725',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Green Mile',
    Year: '1999',
    Rated: 'R',
    Released: '10 Dec 1999',
    Runtime: '189 min',
    Genre: 'Crime, Drama, Fantasy',
    Director: 'Frank Darabont',
    Writer: 'Stephen King, Frank Darabont',
    Actors: 'Tom Hanks, Michael Clarke Duncan, David Morse',
    Plot: "A tale set on death row, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the lead guard, Paul Edgecombe, recognizes John's gift, he tries to help stave off the condemned man's execution.",
    Language: 'English, French',
    Country: 'United States',
    Awards: 'Nominated for 4 Oscars. 15 wins & 37 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '79%' },
      { Source: 'Metacritic', Value: '61/100' },
    ],
    Metascore: '61',
    imdbRating: '8.6',
    imdbVotes: '1,415,284',
    imdbID: 'tt0120689',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$136,801,374',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'City of God',
    Year: '2002',
    Rated: 'R',
    Released: '13 Feb 2004',
    Runtime: '130 min',
    Genre: 'Crime, Drama',
    Director: 'Fernando Meirelles, Kátia Lund',
    Writer: 'Paulo Lins, Bráulio Mantovani',
    Actors: 'Alexandre Rodrigues, Leandro Firmino, Matheus Nachtergaele',
    Plot: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
    Language: 'Portuguese',
    Country: 'Brazil, France, Germany',
    Awards: 'Nominated for 4 Oscars. 75 wins & 50 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMGU5OWEwZDItNmNkMC00NzZmLTk1YTctNzVhZTJjM2NlZTVmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '91%' },
      { Source: 'Metacritic', Value: '79/100' },
    ],
    Metascore: '79',
    imdbRating: '8.6',
    imdbVotes: '805,002',
    imdbID: 'tt0317248',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$7,564,459',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Life Is Beautiful',
    Year: '1997',
    Rated: 'PG-13',
    Released: '20 Dec 1997',
    Runtime: '116 min',
    Genre: 'Comedy, Drama, Romance',
    Director: 'Roberto Benigni',
    Writer: 'Vincenzo Cerami, Roberto Benigni',
    Actors: 'Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini',
    Plot: 'When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.',
    Language: 'Italian, German, English',
    Country: 'Italy',
    Awards: 'Won 3 Oscars. 72 wins & 52 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '81%' },
      { Source: 'Metacritic', Value: '59/100' },
    ],
    Metascore: '59',
    imdbRating: '8.6',
    imdbVotes: '747,039',
    imdbID: 'tt0118799',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$57,563,264',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Seven Samurai',
    Year: '1954',
    Rated: 'Not Rated',
    Released: '19 Nov 1956',
    Runtime: '207 min',
    Genre: 'Action, Drama',
    Director: 'Akira Kurosawa',
    Writer: 'Akira Kurosawa, Shinobu Hashimoto, Hideo Oguni',
    Actors: 'Toshirô Mifune, Takashi Shimura, Keiko Tsushima',
    Plot: 'Farmers from a village exploited by bandits hire a veteran samurai for protection, who gathers six other samurai to join him.',
    Language: 'Japanese',
    Country: 'Japan',
    Awards: 'Nominated for 2 Oscars. 5 wins & 9 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOGNiY2QzOTAtOWNlZC00NjAwLWFmMTAtNTJhYTBiNTY4ODU0XkEyXkFqcGdeQXVyMTQyMTMwOTk0._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '100%' },
      { Source: 'Metacritic', Value: '98/100' },
    ],
    Metascore: '98',
    imdbRating: '8.6',
    imdbVotes: '368,368',
    imdbID: 'tt0047478',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$318,649',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: "It's a Wonderful Life",
    Year: '1946',
    Rated: 'PG',
    Released: '07 Jan 1947',
    Runtime: '130 min',
    Genre: 'Drama, Family, Fantasy',
    Director: 'Frank Capra',
    Writer: 'Frances Goodrich, Albert Hackett, Frank Capra',
    Actors: 'James Stewart, Donna Reed, Lionel Barrymore',
    Plot: 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.',
    Language: 'English, French',
    Country: 'United States',
    Awards: 'Nominated for 5 Oscars. 7 wins & 6 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '94%' },
      { Source: 'Metacritic', Value: '89/100' },
    ],
    Metascore: '89',
    imdbRating: '8.6',
    imdbVotes: '502,178',
    imdbID: 'tt0038650',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$1,483,643',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Harakiri',
    Year: '1962',
    Rated: 'Not Rated',
    Released: '04 Aug 1964',
    Runtime: '133 min',
    Genre: 'Action, Drama, Mystery',
    Director: 'Masaki Kobayashi',
    Writer: 'Yasuhiko Takiguchi, Shinobu Hashimoto',
    Actors: 'Tatsuya Nakadai, Akira Ishihama, Shima Iwashita',
    Plot: "When a ronin requesting seppuku at a feudal lord's palace is told of the brutal suicide of another ronin who previously visited, he reveals how their pasts are intertwined - and in doing so challenges the clan's integrity.",
    Language: 'Japanese',
    Country: 'Japan',
    Awards: '9 wins & 3 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMWNmYzg5NWYtNzhiMS00NzlkLTgyOTUtYzM3MjY0NDc2YjFkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '100%' },
      { Source: 'Metacritic', Value: '85/100' },
    ],
    Metascore: '85',
    imdbRating: '8.6',
    imdbVotes: '69,542',
    imdbID: 'tt0056058',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Gladiator',
    Year: '2000',
    Rated: 'R',
    Released: '05 May 2000',
    Runtime: '155 min',
    Genre: 'Action, Adventure, Drama',
    Director: 'Ridley Scott',
    Writer: 'David Franzoni, John Logan, William Nicholson',
    Actors: 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
    Plot: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    Language: 'English',
    Country: 'United States, United Kingdom, Malta, Morocco',
    Awards: 'Won 5 Oscars. 60 wins & 104 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '80%' },
      { Source: 'Metacritic', Value: '67/100' },
    ],
    Metascore: '67',
    imdbRating: '8.5',
    imdbVotes: '1,628,543',
    imdbID: 'tt0172495',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$187,705,427',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Back to the Future',
    Year: '1985',
    Rated: 'PG',
    Released: '03 Jul 1985',
    Runtime: '116 min',
    Genre: 'Adventure, Comedy, Sci-Fi',
    Director: 'Robert Zemeckis',
    Writer: 'Robert Zemeckis, Bob Gale',
    Actors: 'Michael J. Fox, Christopher Lloyd, Lea Thompson',
    Plot: 'Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 1 Oscar. 25 wins & 25 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '93%' },
      { Source: 'Metacritic', Value: '87/100' },
    ],
    Metascore: '87',
    imdbRating: '8.5',
    imdbVotes: '1,314,080',
    imdbID: 'tt0088763',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$214,077,472',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Alien',
    Year: '1979',
    Rated: 'R',
    Released: '22 Jun 1979',
    Runtime: '117 min',
    Genre: 'Horror, Sci-Fi',
    Director: 'Ridley Scott',
    Writer: "Dan O'Bannon, Ronald Shusett",
    Actors: 'Sigourney Weaver, Tom Skerritt, John Hurt',
    Plot: 'The crew of a commercial spacecraft encounters a deadly lifeform after investigating a mysterious transmission of unknown origin.',
    Language: 'English',
    Country: 'United Kingdom, United States',
    Awards: 'Won 1 Oscar. 19 wins & 22 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '93%' },
      { Source: 'Metacritic', Value: '89/100' },
    ],
    Metascore: '89',
    imdbRating: '8.5',
    imdbVotes: '959,377',
    imdbID: 'tt0078748',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$84,206,106',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Parasite',
    Year: '2019',
    Rated: 'R',
    Released: '08 Nov 2019',
    Runtime: '132 min',
    Genre: 'Drama, Thriller',
    Director: 'Bong Joon Ho',
    Writer: 'Bong Joon Ho, Han Jin-won',
    Actors: 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong',
    Plot: 'Greed and class discrimination threaten the newly-formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    Language: 'Korean, English',
    Country: 'South Korea',
    Awards: 'Won 4 Oscars. 309 wins & 265 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '99%' },
      { Source: 'Metacritic', Value: '96/100' },
    ],
    Metascore: '96',
    imdbRating: '8.5',
    imdbVotes: '975,195',
    imdbID: 'tt6751668',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$53,369,749',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Departed',
    Year: '2006',
    Rated: 'R',
    Released: '06 Oct 2006',
    Runtime: '151 min',
    Genre: 'Crime, Drama, Thriller',
    Director: 'Martin Scorsese',
    Writer: 'William Monahan, Alan Mak, Felix Chong',
    Actors: 'Leonardo DiCaprio, Matt Damon, Jack Nicholson',
    Plot: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
    Language: 'English, Cantonese',
    Country: 'United States, Hong Kong',
    Awards: 'Won 4 Oscars. 99 wins & 141 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '91%' },
      { Source: 'Metacritic', Value: '85/100' },
    ],
    Metascore: '85',
    imdbRating: '8.5',
    imdbVotes: '1,429,007',
    imdbID: 'tt0407887',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$132,399,394',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Django Unchained',
    Year: '2012',
    Rated: 'R',
    Released: '25 Dec 2012',
    Runtime: '165 min',
    Genre: 'Comedy, Drama, Western',
    Director: 'Quentin Tarantino',
    Writer: 'Quentin Tarantino',
    Actors: 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio',
    Plot: 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.',
    Language: 'English, German, French, Italian',
    Country: 'United States',
    Awards: 'Won 2 Oscars. 58 wins & 158 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '87%' },
      { Source: 'Metacritic', Value: '81/100' },
    ],
    Metascore: '81',
    imdbRating: '8.5',
    imdbVotes: '1,705,452',
    imdbID: 'tt1853728',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$162,805,434',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Prestige',
    Year: '2006',
    Rated: 'PG-13',
    Released: '20 Oct 2006',
    Runtime: '130 min',
    Genre: 'Drama, Mystery, Sci-Fi',
    Director: 'Christopher Nolan',
    Writer: 'Jonathan Nolan, Christopher Nolan, Christopher Priest',
    Actors: 'Christian Bale, Hugh Jackman, Scarlett Johansson',
    Plot: 'After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
    Language: 'English',
    Country: 'United Kingdom, United States',
    Awards: 'Nominated for 2 Oscars. 6 wins & 44 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTM3MzQ5MjQ5OF5BMl5BanBnXkFtZTcwMTQ3NzMzMw@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '77%' },
      { Source: 'Metacritic', Value: '66/100' },
    ],
    Metascore: '66',
    imdbRating: '8.5',
    imdbVotes: '1,451,983',
    imdbID: 'tt0482571',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$53,089,891',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Léon: The Professional',
    Year: '1994',
    Rated: 'R',
    Released: '18 Nov 1994',
    Runtime: '110 min',
    Genre: 'Action, Crime, Drama',
    Director: 'Luc Besson',
    Writer: 'Luc Besson',
    Actors: 'Jean Reno, Gary Oldman, Natalie Portman',
    Plot: "12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade.",
    Language: 'English, Italian, French',
    Country: 'France, United States',
    Awards: '5 wins & 16 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOTgyMWQ0ZWUtN2Q2MS00NmY0LWI3OWMtNjFkMzZlNDZjNTk0XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '75%' },
      { Source: 'Metacritic', Value: '64/100' },
    ],
    Metascore: '64',
    imdbRating: '8.5',
    imdbVotes: '1,252,570',
    imdbID: 'tt0110413',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$19,501,238',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Whiplash',
    Year: '2014',
    Rated: 'R',
    Released: '15 Oct 2014',
    Runtime: '106 min',
    Genre: 'Drama, Music',
    Director: 'Damien Chazelle',
    Writer: 'Damien Chazelle',
    Actors: 'Miles Teller, J.K. Simmons, Melissa Benoist',
    Plot: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 3 Oscars. 98 wins & 144 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '94%' },
      { Source: 'Metacritic', Value: '89/100' },
    ],
    Metascore: '89',
    imdbRating: '8.5',
    imdbVotes: '1,002,639',
    imdbID: 'tt2582802',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$13,092,000',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Lion King',
    Year: '1994',
    Rated: 'G',
    Released: '24 Jun 1994',
    Runtime: '88 min',
    Genre: 'Animation, Adventure, Drama',
    Director: 'Roger Allers, Rob Minkoff',
    Writer: 'Irene Mecchi, Jonathan Roberts, Linda Woolverton',
    Actors: 'Matthew Broderick, Jeremy Irons, James Earl Jones',
    Plot: 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
    Language: 'English, Swahili, Xhosa, Zulu',
    Country: 'United States',
    Awards: 'Won 2 Oscars. 43 wins & 35 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '92%' },
      { Source: 'Metacritic', Value: '88/100' },
    ],
    Metascore: '88',
    imdbRating: '8.5',
    imdbVotes: '1,148,802',
    imdbID: 'tt0110357',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$422,783,777',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Usual Suspects',
    Year: '1995',
    Rated: 'R',
    Released: '16 Aug 1995',
    Runtime: '106 min',
    Genre: 'Crime, Drama, Mystery',
    Director: 'Bryan Singer',
    Writer: 'Christopher McQuarrie',
    Actors: 'Kevin Spacey, Gabriel Byrne, Chazz Palminteri',
    Plot: 'The sole survivor of a pier shoot-out tells the story of how a notorious criminal influenced the events that began with five criminals meeting in a seemingly random police lineup.',
    Language: 'English, Hungarian, Spanish, French',
    Country: 'Germany, United States',
    Awards: 'Won 2 Oscars. 37 wins & 17 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '87%' },
      { Source: 'Metacritic', Value: '77/100' },
    ],
    Metascore: '77',
    imdbRating: '8.5',
    imdbVotes: '1,149,941',
    imdbID: 'tt0114814',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$23,341,568',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'American History X',
    Year: '1998',
    Rated: 'R',
    Released: '20 Nov 1998',
    Runtime: '119 min',
    Genre: 'Crime, Drama',
    Director: 'Tony Kaye',
    Writer: 'David McKenna',
    Actors: "Edward Norton, Edward Furlong, Beverly D'Angelo",
    Plot: 'Living a life marked by violence, neo-Nazi Derek finally goes to prison after killing two black youths. Upon his release, Derek vows to change; he hopes to prevent his brother, Danny, who idolizes Derek, from following in his foot...',
    Language: 'English',
    Country: 'United States',
    Awards: 'Nominated for 1 Oscar. 4 wins & 15 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZTJhN2FkYWEtMGI0My00YWM4LWI2MjAtM2UwNjY4MTI2ZTQyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '84%' },
      { Source: 'Metacritic', Value: '62/100' },
    ],
    Metascore: '62',
    imdbRating: '8.5',
    imdbVotes: '1,191,108',
    imdbID: 'tt0120586',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$6,719,864',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Casablanca',
    Year: '1942',
    Rated: 'PG',
    Released: '23 Jan 1943',
    Runtime: '102 min',
    Genre: 'Drama, Romance, War',
    Director: 'Michael Curtiz',
    Writer: 'Julius J. Epstein, Philip G. Epstein, Howard Koch',
    Actors: 'Humphrey Bogart, Ingrid Bergman, Paul Henreid',
    Plot: 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.',
    Language: 'English, French, German, Italian, Russian',
    Country: 'United States',
    Awards: 'Won 3 Oscars. 14 wins & 11 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '99%' },
      { Source: 'Metacritic', Value: '100/100' },
    ],
    Metascore: '100',
    imdbRating: '8.5',
    imdbVotes: '609,546',
    imdbID: 'tt0034583',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$4,219,709',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Pianist',
    Year: '2002',
    Rated: 'R',
    Released: '28 Mar 2003',
    Runtime: '150 min',
    Genre: 'Biography, Drama, Music',
    Director: 'Roman Polanski',
    Writer: 'Ronald Harwood, Wladyslaw Szpilman',
    Actors: 'Adrien Brody, Thomas Kretschmann, Frank Finlay',
    Plot: 'During WWII, acclaimed Polish musician Wladyslaw faces various struggles as he loses contact with his family. As the situation worsens, he hides in the ruins of Warsaw in order to survive.',
    Language: 'English, German, Russian',
    Country: 'France, Poland, Germany, United Kingdom, United States',
    Awards: 'Won 3 Oscars. 57 wins & 74 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '95%' },
      { Source: 'Metacritic', Value: '85/100' },
    ],
    Metascore: '85',
    imdbRating: '8.5',
    imdbVotes: '919,051',
    imdbID: 'tt0253474',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$32,590,750',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Psycho',
    Year: '1960',
    Rated: 'R',
    Released: '08 Sep 1960',
    Runtime: '109 min',
    Genre: 'Horror, Mystery, Thriller',
    Director: 'Alfred Hitchcock',
    Writer: 'Joseph Stefano, Robert Bloch',
    Actors: 'Anthony Perkins, Janet Leigh, Vera Miles',
    Plot: 'A secretary on the run for embezzlement takes refuge at a secluded California motel owned by a repressed man and his overbearing mother.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Nominated for 4 Oscars. 8 wins & 14 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '97%' },
      { Source: 'Metacritic', Value: '97/100' },
    ],
    Metascore: '97',
    imdbRating: '8.5',
    imdbVotes: '721,707',
    imdbID: 'tt0054215',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$32,000,000',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Once Upon a Time in the West',
    Year: '1968',
    Rated: 'PG-13',
    Released: '04 Jul 1969',
    Runtime: '166 min',
    Genre: 'Drama, Western',
    Director: 'Sergio Leone',
    Writer: 'Sergio Donati, Sergio Leone, Dario Argento',
    Actors: 'Henry Fonda, Charles Bronson, Claudia Cardinale',
    Plot: 'A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.',
    Language: 'Italian, English, Spanish',
    Country: 'Italy, United States',
    Awards: '6 wins & 5 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BODQ3NDExOGYtMzI3Mi00NWRlLTkwNjAtNjc4MDgzZGJiZTA1XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.5/10' },
      { Source: 'Rotten Tomatoes', Value: '96%' },
      { Source: 'Metacritic', Value: '82/100' },
    ],
    Metascore: '82',
    imdbRating: '8.5',
    imdbVotes: '350,680',
    imdbID: 'tt0064116',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$5,321,508',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
];
